### ISSUE TITLE
Wrong font link in the cask for font-anonymous-pro

### ISSUE THREAD

**Issue by andrew-lozoya** [Homebrew/homebrew-cask-fonts#2720]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

Wrong link in the cask for font-anonymous-pro, 

Should be https://www.marksimonson.com/assets/content/fonts/AnonymousPro-1_002.zip, not https://www.marksimonson.com/assets/content/fonts/AnonymousPro-1.002.zip

See: https://github.com/Homebrew/homebrew-cask-fonts/blob/40b132f111dae71032287dbba323e0d758b003e6/Casks/font-anonymous-pro.rb#L2

#### Command that failed

```
brew cask install font-anonymous-pro
```

#### Output of command with `--verbose --debug`

```
brew cask install font-anonymous-pro --verbose --debug
Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Downloading
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.0-16-g77b4275\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.0.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://www.marksimonson.com/assets/content/fonts/AnonymousPro-1.002.zip
==> Downloading https://www.marksimonson.com/assets/content/fonts/AnonymousPro-1.002.zip
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.0-16-g77b4275\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.0.1\)\ curl/7.64.1 --header Accept-Language:\ en --retry 3 --location --range 0-1 --dump-header - --write-out \%\{http_code\} --output /dev/null https://www.marksimonson.com/assets/content/fonts/AnonymousPro-1.002.zip
/usr/bin/curl --disable --globoff --show-error --user-agent Homebrew/2.6.0-16-g77b4275\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 11.0.1\)\ curl/7.64.1 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --continue-at 0 --output /Users/alozoya/Library/Caches/Homebrew/downloads/41f3a9742ca5c79839d25f52645f70851982ef1284a082a33207880d61f2d953--AnonymousPro-1.002.zip.incomplete https://www.marksimonson.com/assets/content/fonts/AnonymousPro-1.002.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Error: Download failed on Cask 'font-anonymous-pro' with message: Download failed: https://www.marksimonson.com/assets/content/fonts/AnonymousPro-1.002.zip
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:375:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:372:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:24:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:157:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:174:in `primary_container'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:317:in `collect_cask_and_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:344:in `cask_and_formula_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:253:in `satisfy_dependencies'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:67:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:94:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:79:in `block in install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:78:in `install_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:43:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:108:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:183:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:117:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:15:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:188:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:188:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:165:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:117:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:15:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:119:in `<main>'
```

#### Output of `brew doctor --verbose`

```
brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.10.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rspec-its-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ronn-0.7.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rainbow-3.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/webrobots-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ntlm-http-0.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mini_portile2-2.4.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/http-cookie-1.0.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/hpricot-0.8.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/extensions/universal-darwin-19/2.6.0/hpricot-0.8.6
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/unf-0.1.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/docile-1.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.5/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin20
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20
/usr/local/Homebrew/Library/Homebrew
==> Homebrew Version
2.6.0-16-g77b4275
==> macOS
11.0.1
==> SIP
Enabled
==> Java
1.8.261.12, 1.8.0_261
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3733 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (167 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1570 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (166 casks)
```

#### Output of `brew tap`

```
aws/tap
bazelbuild/tap
cjbassi/ytop
cloudfoundry/tap
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
homebrew/services
nodesource/nsolid
pivotal/tap
prospectone/perfops
sambadevi/powerlevel9k
teamookla/speedtest
weaveworks/tap
```

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask-fonts/pull/2728
