### ISSUE TITLE
Roboto Font installed has possible unicode or table errors

### ISSUE THREAD

**Issue by andrewvaughan** [Homebrew/homebrew-cask-fonts#3389]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

After installing the `Roboto` font with `brew install --cask font-roboto`, the font that gets installed has the name "Spcpup" and scrambles all characters in the text:

![Roboto-Failure](https://user-images.githubusercontent.com/1119590/104612657-72e84b80-5654-11eb-93af-bda299d1bb2e.png)

Further inspection shows that the installed font seems fine, but every application has the problem shown above:

```
$ brew install lcdf-typetools

// ...clipped...

$ otfinfo --info /Users/andrew/Library/Fonts/Roboto\[wdth,wght\].ttf
Family:              Roboto
Subfamily:           Regular
Full name:           Roboto
PostScript name:     Roboto-Regular
Version:             Version 3.004; 2020
Unique ID:           Roboto
Designer:            Christian Robertson
Designer URL:        Google.com
Manufacturer:        Google
Vendor URL:          Google.com
Trademark:           Roboto is a trademark of Google.
Copyright:           Copyright 2011 Google Inc. All Rights Reserved.
License URL:         http://www.apache.org/licenses/LICENSE-2.0
License Description: Licensed under the Apache License, Version 2.0
```

It does, however, show that the installed file has a bad table name:

```
$ otfinfo --dump-table /Users/andrew/Library/Fonts/Roboto\[wdth,wght\].ttf
otfinfo: bad table name
```

#### Command that failed

```
$ brew install --cask font-roboto
```

#### Output of command with `--verbose --debug`

```
$  brew install --cask --verbose --debug --force font-roboto 
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
svn info
svn switch https://github.com/google/fonts/trunk/apache/roboto /Users/andrew/Library/Caches/Homebrew/Cask/font-roboto--svn
==> Cloning https://github.com/google/fonts/trunk/apache/roboto
Updating /Users/andrew/Library/Caches/Homebrew/Cask/font-roboto--svn
svn update --trust-server-cert --non-interactive
Updating '.':
At revision 10359.
==> Checking quarantine support
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/andrew/Library/Caches/Homebrew/Cask/font-roboto--svn
/usr/bin/xattr -p com.apple.quarantine /Users/andrew/Library/Caches/Homebrew/Cask/font-roboto--svn
==> /Users/andrew/Library/Caches/Homebrew/Cask/font-roboto--svn is quarantined
Warning: No checksum defined for cask 'font-roboto', skipping verification.
hdiutil imageinfo -format /Users/andrew/Library/Caches/Homebrew/Cask/font-roboto--svn
==> Installing Cask font-roboto
==> Cask::Installer#stage
==> Extracting primary container
==> Using container class UnpackStrategy::Subversion for /Users/andrew/Library/Caches/Homebrew/Cask/font-roboto--svn
svn export --force . /var/folders/bx/1hy3vprx3512y62mqz9yzp7m0000gn/T/d20210114-60017-i65jxj
cp -pR /var/folders/bx/1hy3vprx3512y62mqz9yzp7m0000gn/T/d20210114-60017-i65jxj/METADATA.pb /usr/local/Caskroom/font-roboto/latest/METADATA.pb
cp -pR /var/folders/bx/1hy3vprx3512y62mqz9yzp7m0000gn/T/d20210114-60017-i65jxj/Roboto-Italic\[wdth,wght\].ttf /usr/local/Caskroom/font-roboto/latest/Roboto-Italic\[wdth,wght\].ttf
cp -pR /var/folders/bx/1hy3vprx3512y62mqz9yzp7m0000gn/T/d20210114-60017-i65jxj/static/. /usr/local/Caskroom/font-roboto/latest/static
cp -pR /var/folders/bx/1hy3vprx3512y62mqz9yzp7m0000gn/T/d20210114-60017-i65jxj/OFL.txt /usr/local/Caskroom/font-roboto/latest/OFL.txt
cp -pR /var/folders/bx/1hy3vprx3512y62mqz9yzp7m0000gn/T/d20210114-60017-i65jxj/Roboto\[wdth,wght\].ttf /usr/local/Caskroom/font-roboto/latest/Roboto\[wdth,wght\].ttf
cp -pR /var/folders/bx/1hy3vprx3512y62mqz9yzp7m0000gn/T/d20210114-60017-i65jxj/DESCRIPTION.en_us.html /usr/local/Caskroom/font-roboto/latest/DESCRIPTION.en_us.html
cp -pR /var/folders/bx/1hy3vprx3512y62mqz9yzp7m0000gn/T/d20210114-60017-i65jxj/LICENSE.txt /usr/local/Caskroom/font-roboto/latest/LICENSE.txt
chmod -Rf +w /var/folders/bx/1hy3vprx3512y62mqz9yzp7m0000gn/T/d20210114-60017-i65jxj
==> Verifying Gatekeeper status of /Users/andrew/Library/Caches/Homebrew/Cask/font-roboto--svn
/usr/bin/xattr -p com.apple.quarantine /Users/andrew/Library/Caches/Homebrew/Cask/font-roboto--svn
==> /Users/andrew/Library/Caches/Homebrew/Cask/font-roboto--svn is quarantined
==> Propagating quarantine from /Users/andrew/Library/Caches/Homebrew/Cask/font-roboto--svn to /usr/local/Caskroom/font-roboto/latest
/usr/bin/xattr -p com.apple.quarantine /Users/andrew/Library/Caches/Homebrew/Cask/font-roboto--svn
/usr/bin/xargs -0 -- /bin/chmod -h u\+w
/usr/bin/xargs -0 -- /usr/bin/xattr -w com.apple.quarantine 0181\;60006305\;Homebrew\\x20Cask\;6CAC21E0-20A2-41EB-8BB4-809F52ABF2A4
==> Creating metadata directory /usr/local/Caskroom/font-roboto/.metadata/latest/20210114154326.788.
==> Creating metadata subdirectory /usr/local/Caskroom/font-roboto/.metadata/latest/20210114154326.788/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet: {#<Cask::Artifact::Font:0x00007fdfca9c0e80 @cask=#<Cask::Cask:0x00007fdfcc0ffce0 @token="font-roboto", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts/Casks/font-roboto.rb>, @tap=#<Tap:0x00007fdfcc0cc728 @user="Homebrew", @repo="cask-fonts", @name="homebrew/cask-fonts", @full_name="Homebrew/homebrew-cask-fonts", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts/Casks>>, @block=#<Proc:0x00007fdfcc0ffc40@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts/Casks/font-roboto.rb:1>, @default_config=#<Cask::Config:0x00007fdfcc0ee670 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/font-roboto>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/font-roboto/.metadata>, @config=#<Cask::Config:0x00007fdfca9c1d08 @explicit={}, @default={:languages=>["en-US"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/andrew/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/andrew/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/andrew/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/andrew/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/andrew/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/andrew/Library/Fonts>, :servicedir=>#<Pathname:/Users/andrew/Library/Services>, :input_methoddir=>#<Pathname:/Users/andrew/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/andrew/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/andrew/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/andrew/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/andrew/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/andrew/Library/Screen Savers>}, @env={}>, @dsl=#<Cask::DSL:0x00007fdfca9c1ad8 @cask=#<Cask::Cask:0x00007fdfcc0ffce0 ...>, @token="font-roboto", @version="latest", @sha256=:no_check, @url=#<URL:0x00007fdfca9c14e8 @uri=#<URI::HTTPS https://github.com/google/fonts/trunk/apache/roboto>, @verified="github.com/google/fonts/", @using=:svn, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=true, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:verified=>"github.com/google/fonts/", :using=>:svn, :trust_cert=>true, :user_agent=>:default}, @from_block=false, @caller_location="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts/Casks/font-roboto.rb:5:in `block in load'">, @name=["Roboto"], @homepage="https://fonts.google.com/specimen/Roboto", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/font-roboto/latest>, @language_eval=nil>>, @source_string="Roboto-Italic[wdth,wght].ttf", @target_string="", @source=#<Pathname:/usr/local/Caskroom/font-roboto/latest/Roboto-Italic[wdth,wght].ttf>, @target=#<Pathname:/Users/andrew/Library/Fonts/Roboto-Italic[wdth,wght].ttf>>, #<Cask::Artifact::Font:0x00007fdfca9ca750 @cask=#<Cask::Cask:0x00007fdfcc0ffce0 @token="font-roboto", @sourcefile_path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts/Casks/font-roboto.rb>, @tap=#<Tap:0x00007fdfcc0cc728 @user="Homebrew", @repo="cask-fonts", @name="homebrew/cask-fonts", @full_name="Homebrew/homebrew-cask-fonts", @path=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts>, @alias_table=nil, @alias_reverse_table=nil, @formula_renames={}, @cask_dir=#<Pathname:/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts/Casks>>, @block=#<Proc:0x00007fdfcc0ffc40@/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts/Casks/font-roboto.rb:1>, @default_config=#<Cask::Config:0x00007fdfcc0ee670 @explicit={}>, @caskroom_path=#<Pathname:/usr/local/Caskroom/font-roboto>, @metadata_master_container_path=#<Pathname:/usr/local/Caskroom/font-roboto/.metadata>, @config=#<Cask::Config:0x00007fdfca9c1d08 @explicit={}, @default={:languages=>["en-US"], :appdir=>#<Pathname:/Applications>, :colorpickerdir=>#<Pathname:/Users/andrew/Library/ColorPickers>, :prefpanedir=>#<Pathname:/Users/andrew/Library/PreferencePanes>, :qlplugindir=>#<Pathname:/Users/andrew/Library/QuickLook>, :mdimporterdir=>#<Pathname:/Users/andrew/Library/Spotlight>, :dictionarydir=>#<Pathname:/Users/andrew/Library/Dictionaries>, :fontdir=>#<Pathname:/Users/andrew/Library/Fonts>, :servicedir=>#<Pathname:/Users/andrew/Library/Services>, :input_methoddir=>#<Pathname:/Users/andrew/Library/Input Methods>, :internet_plugindir=>#<Pathname:/Users/andrew/Library/Internet Plug-Ins>, :audio_unit_plugindir=>#<Pathname:/Users/andrew/Library/Audio/Plug-Ins/Components>, :vst_plugindir=>#<Pathname:/Users/andrew/Library/Audio/Plug-Ins/VST>, :vst3_plugindir=>#<Pathname:/Users/andrew/Library/Audio/Plug-Ins/VST3>, :screen_saverdir=>#<Pathname:/Users/andrew/Library/Screen Savers>}, @env={}>, @dsl=#<Cask::DSL:0x00007fdfca9c1ad8 @cask=#<Cask::Cask:0x00007fdfcc0ffce0 ...>, @token="font-roboto", @version="latest", @sha256=:no_check, @url=#<URL:0x00007fdfca9c14e8 @uri=#<URI::HTTPS https://github.com/google/fonts/trunk/apache/roboto>, @verified="github.com/google/fonts/", @using=:svn, @tag=nil, @branch=nil, @revisions=nil, @revision=nil, @trust_cert=true, @cookies=nil, @referer=nil, @header=nil, @user_agent=:default, @data=nil, @specs={:verified=>"github.com/google/fonts/", :using=>:svn, :trust_cert=>true, :user_agent=>:default}, @from_block=false, @caller_location="/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts/Casks/font-roboto.rb:5:in `block in load'">, @name=["Roboto"], @homepage="https://fonts.google.com/specimen/Roboto", @artifacts=#<SortedSet: {...}>, @staged_path=#<Pathname:/usr/local/Caskroom/font-roboto/latest>, @language_eval=nil>>, @source_string="Roboto[wdth,wght].ttf", @target_string="", @source=#<Pathname:/usr/local/Caskroom/font-roboto/latest/Roboto[wdth,wght].ttf>, @target=#<Pathname:/Users/andrew/Library/Fonts/Roboto[wdth,wght].ttf>>}>
==> Installing artifact of class Cask::Artifact::Font
Warning: It seems there is already a Font at '/Users/andrew/Library/Fonts/Roboto-Italic[wdth,wght].ttf'; overwriting.
==> Removing Font '/Users/andrew/Library/Fonts/Roboto-Italic[wdth,wght].ttf'.
==> Moving Font 'Roboto-Italic[wdth,wght].ttf' to '/Users/andrew/Library/Fonts/Roboto-Italic[wdth,wght].ttf'.
==> Installing artifact of class Cask::Artifact::Font
Warning: It seems there is already a Font at '/Users/andrew/Library/Fonts/Roboto[wdth,wght].ttf'; overwriting.
==> Removing Font '/Users/andrew/Library/Fonts/Roboto[wdth,wght].ttf'.
==> Moving Font 'Roboto[wdth,wght].ttf' to '/Users/andrew/Library/Fonts/Roboto[wdth,wght].ttf'.
/usr/local/Homebrew/Library/Homebrew/shims/scm/git --version
🍺  font-roboto was successfully installed!
```

#### Output of `brew doctor --verbose`

```
$ brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/sorbet-runtime-stub-0.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-sorbet-0.5.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-2.1.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rails-2.9.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.9.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rack-2.2.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.6.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/patchelf-1.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/elftools-1.1.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/simplecov_json_formatter-0.1.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/bindata-2.4.8/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.1.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.4.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-2.0.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin20
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20
/usr/local/Homebrew/Library/Homebrew
/usr/bin/xattr
/usr/bin/swift /usr/local/Homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Homebrew Version
2.7.4
==> macOS
11.0.1
==> SIP
Enabled
/usr/libexec/java_home --xml --failfast
==> Java
15.0.1
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3790 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-versions (175 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1600 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers (170 casks)
/usr/bin/xattr
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Some installed kegs have no formulae!
This means they were either deleted or installed with `brew diy`.
You should find replacements for the following formulae:
  unrar
```

#### Output of `brew tap`

```
$ brew tap
homebrew/cask
homebrew/cask-drivers
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
```

**Comment by andrewvaughan** [comment]
Closing this issue - it seems as if this is something wrong specifically with Microsoft products on macOS. Thanks!
