### ISSUE TITLE
Existing font cask fails to upgrade

### ISSUE THREAD

**Issue by jgmarcel** [Homebrew/homebrew-cask-fonts#6999]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

Cask fails to upgrade with message `No cask with this name exists`.

### Command that failed

`brew upgrade --cask --force font-sometype-mono`

### Output of command with `--verbose --debug`

```shell
$ brew upgrade --cask --force --verbose --debug font-sometype-mono
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.19-12-g260ee0e\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.1\)\ curl/7.85.0 --header Accept-Language:\ en --retry 3 --location --silent --head --request GET https://github.com/dharmatype/Sometype-Mono/archive/master.zip
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.19-12-g260ee0e\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.1\)\ curl/7.85.0 --header Accept-Language:\ en --retry 3 --location --head https://codeload.github.com/dharmatype/Sometype-Mono/zip/refs/heads/master
/opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/3.6.19-12-g260ee0e\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.1\)\ curl/7.85.0 --header Accept-Language:\ en --fail --retry 3 --location --remote-time --output /Users/jientile/Library/Caches/Homebrew/downloads/e7293031933033013e45ffa8aa7de11a14d56f8a2c459bc0c0a7456d10329e26--Sometype-Mono-master.zip.incomplete https://codeload.github.com/dharmatype/Sometype-Mono/zip/refs/heads/master
==> Checking quarantine support
/usr/bin/xattr -h
/usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift
==> Quarantine is available.
==> Verifying Gatekeeper status of /Users/jientile/Library/Caches/Homebrew/downloads/e7293031933033013e45ffa8aa7de11a14d56f8a2c459bc0c0a7456d10329e26--Sometype-Mono-master.zip
/usr/bin/xattr -p com.apple.quarantine /Users/jientile/Library/Caches/Homebrew/downloads/e7293031933033013e45ffa8aa7de11a14d56f8a2c459bc0c0a7456d10329e26--Sometype-Mono-master.zip
==> /Users/jientile/Library/Caches/Homebrew/downloads/e7293031933033013e45ffa8aa7de11a14d56f8a2c459bc0c0a7456d10329e26--Sometype-Mono-master.zip is not quarantined
==> Quarantining /Users/jientile/Library/Caches/Homebrew/downloads/e7293031933033013e45ffa8aa7de11a14d56f8a2c459bc0c0a7456d10329e26--Sometype-Mono-master.zip
/usr/bin/swift -target arm64-apple-macosx13 /opt/homebrew/Library/Homebrew/cask/utils/quarantine.swift /Users/jientile/Library/Caches/Homebrew/downloads/e7293031933033013e45ffa8aa7de11a14d56f8a2c459bc0c0a7456d10329e26--Sometype-Mono-master.zip https://github.com/dharmatype/Sometype-Mono/archive/master.zip https://monospacedfont.com/
==> Upgrading 1 outdated package:
Error: Cask 'font-sometype-mono' is unavailable: No Cask with this name exists.
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:306:in `load'
/opt/homebrew/Library/Homebrew/cask/cask_loader.rb:315:in `load'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `block in upgrade_casks'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `map'
/opt/homebrew/Library/Homebrew/cask/cmd/upgrade.rb:149:in `upgrade_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:226:in `upgrade_outdated_casks'
/opt/homebrew/Library/Homebrew/cmd/upgrade.rb:117:in `upgrade'
/opt/homebrew/Library/Homebrew/brew.rb:98:in `<main>'
```

### Output of `brew doctor --verbose`

```shell
$ brew doctor --verbose
==> Cask Environment Variables:
BUNDLE_PATH
CHRUBY_VERSION
GEM_HOME
GEM_PATH
HOMEBREW_CASK_OPTS
LC_ALL
PATH
RBENV_VERSION
RUBYLIB
RUBYOPT
RUBYPATH
SHELL
==> $LOAD_PATHS
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/warning-1.3.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/tapioca-0.7.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/yard-sorbet-0.6.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/yard-0.9.28/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/spoom-1.1.11/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/thor-1.2.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-static-and-runtime-0.5.10461/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-0.5.10461/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-static-0.5.10461-universal-darwin-21/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/simplecov-cobertura-2.1.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/simplecov-0.22.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/simplecov_json_formatter-0.1.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/simplecov-html-0.12.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-macho-3.0.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-sorbet-0.6.11/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-rspec-2.17.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-rails-2.17.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-performance-1.15.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-1.43.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/unicode-display_width-2.4.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ruby-progressbar-1.11.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubocop-ast-1.24.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec_junit_formatter-0.6.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-wait-0.0.9/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-sorbet-1.9.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-retry-0.6.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-its-1.3.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-github-2.4.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-3.12.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-mocks-3.12.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-expectations-3.12.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-core-3.12.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rspec-support-3.12.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ronn-0.7.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rexml-3.2.5/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rdiscount-2.2.7/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/rdiscount-2.2.7
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rbi-0.0.14/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/unparser-0.6.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rack-3.0.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/pry-0.14.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/plist-3.6.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/patchelf-1.4.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parlour-8.1.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/sorbet-runtime-0.5.10461/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rainbow-3.1.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parser-3.2.0.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel_tests-3.13.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/parallel-1.22.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/mustache-1.1.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/method_source-1.0.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/mechanize-2.8.5/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/webrobots-0.1.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/webrick-1.7.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/rubyntlm-0.6.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/nokogiri-1.13.10-x86_64-darwin/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/racc-1.6.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/racc-1.6.2
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/net-http-persistent-4.0.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/net-http-digest_auth-1.4.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/mime-types-3.4.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/mime-types-data-3.2022.0105/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/json_schemer-0.2.24/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/uri_template-0.7.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/json-2.6.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/json-2.6.3
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/http-cookie-1.0.5/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/hpricot-0.8.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/hpricot-0.8.6
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/hana-1.3.7/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/elftools-1.2.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ecma-re-validator-0.4.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/regexp_parser-2.6.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/domain_name-0.5.20190701/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/unf-0.1.4/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/unf_ext-0.0.8.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/unf_ext-0.0.8.2
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/docile-1.4.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/diff-lcs-1.5.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/did_you_mean-1.6.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/connection_pool-2.3.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/highline-2.0.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/coderay-1.1.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/byebug-11.1.3/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/byebug-11.1.3
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.15.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/bootsnap-1.15.0
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/msgpack-1.6.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/extensions/universal-darwin-21/2.6.0/msgpack-1.6.0
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/bindata-2.4.14/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/ast-2.4.2/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/addressable-2.8.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/public_suffix-5.0.1/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.7/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/zeitwerk-2.6.6/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/tzinfo-2.0.5/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/minitest-5.17.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/i18n-1.12.0/lib
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.10/lib/concurrent-ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/arm64e-darwin22
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin22
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/arm64e-darwin22
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin22
/opt/homebrew/Library/Homebrew
==> Homebrew Version
3.6.19-12-g260ee0e
==> macOS
13.1
==> SIP
Disabled
==> Homebrew Cask Staging Location
/opt/homebrew/Caskroom
==> Homebrew Cask Taps:
/opt/homebrew/Library/Taps/homebrew/homebrew-cask (4145 casks)
/opt/homebrew/Library/Taps/homebrew/homebrew-cask-versions (220 casks)
/opt/homebrew/Library/Taps/homebrew/homebrew-cask-fonts (2011 casks)
/opt/homebrew/Library/Taps/oncletom/homebrew-brew (2 casks)
Your system is ready to brew.
```

### Output of `brew tap`

```shell
$ brew tap
coteditor/coteditor
homebrew/cask
homebrew/cask-fonts
homebrew/cask-versions
homebrew/core
nvie/tap
oncletom/brew
potatolabs/git-redate
```

**Comment by bevanjkay** [comment]
@jgmarcel Can you try using the `brew reinstall font-sometype-mono` command instead and see if it succeeds?

**Comment by jgmarcel** [comment]
@bevanjkay It did succeed. Thank you!

`$ brew reinstall font-sometype-mono
==> Downloading https://github.com/dharmatype/Sometype-Mono/archive/master.zip
==> Downloading from https://codeload.github.com/dharmatype/Sometype-Mono/zip/refs/heads/master
######################################################################## 100.0%
Warning: No checksum defined for cask 'font-sometype-mono', skipping verification.
==> Uninstalling Cask font-sometype-mono
==> Backing Font 'SometypeMono-Bold.otf' up to '/opt/homebrew/Caskroom/font-sometype-mono/latest/Sometype-Mono-master/fonts/otf/SometypeMono-
==> Removing Font '/Users/jientile/Library/Fonts/SometypeMono-Bold.otf'
==> Backing Font 'SometypeMono-BoldItalic.otf' up to '/opt/homebrew/Caskroom/font-sometype-mono/latest/Sometype-Mono-master/fonts/otf/Sometyp
==> Removing Font '/Users/jientile/Library/Fonts/SometypeMono-BoldItalic.otf'
==> Backing Font 'SometypeMono-Medium.otf' up to '/opt/homebrew/Caskroom/font-sometype-mono/latest/Sometype-Mono-master/fonts/otf/SometypeMon
==> Removing Font '/Users/jientile/Library/Fonts/SometypeMono-Medium.otf'
==> Backing Font 'SometypeMono-MediumItalic.otf' up to '/opt/homebrew/Caskroom/font-sometype-mono/latest/Sometype-Mono-master/fonts/otf/Somet
==> Removing Font '/Users/jientile/Library/Fonts/SometypeMono-MediumItalic.otf'
==> Backing Font 'SometypeMono-Regular.otf' up to '/opt/homebrew/Caskroom/font-sometype-mono/latest/Sometype-Mono-master/fonts/otf/SometypeMo
==> Removing Font '/Users/jientile/Library/Fonts/SometypeMono-Regular.otf'
==> Backing Font 'SometypeMono-RegularItalic.otf' up to '/opt/homebrew/Caskroom/font-sometype-mono/latest/Sometype-Mono-master/fonts/otf/Some
==> Removing Font '/Users/jientile/Library/Fonts/SometypeMono-RegularItalic.otf'
==> Purging files for version latest of Cask font-sometype-mono
==> Installing Cask font-sometype-mono
Warning: macOS's Gatekeeper has been disabled for this Cask
==> Moving Font 'SometypeMono-Bold.otf' to '/Users/jientile/Library/Fonts/SometypeMono-Bold.otf'
==> Moving Font 'SometypeMono-BoldItalic.otf' to '/Users/jientile/Library/Fonts/SometypeMono-BoldItalic.otf'
==> Moving Font 'SometypeMono-Medium.otf' to '/Users/jientile/Library/Fonts/SometypeMono-Medium.otf'
==> Moving Font 'SometypeMono-MediumItalic.otf' to '/Users/jientile/Library/Fonts/SometypeMono-MediumItalic.otf'
==> Moving Font 'SometypeMono-Regular.otf' to '/Users/jientile/Library/Fonts/SometypeMono-Regular.otf'
==> Moving Font 'SometypeMono-RegularItalic.otf' to '/Users/jientile/Library/Fonts/SometypeMono-RegularItalic.otf'
🍺  font-sometype-mono was successfully installed!`

What do you reckon happened in the first place? Should I refrain from using `brew upgrade` for font casks?

Thank you once again!

**Comment by bevanjkay** [comment]
It is possible that the syntax in the installed version of the cask was unreadable, I wouldn't expect that you would need to refrain from using `brew upgrade` in future.
