### ISSUE TITLE
Can't install fonts on Linux

### ISSUE THREAD

**Issue by Goooler** [Homebrew/homebrew-cask-fonts#7040]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error.

### Description of issue

Try these steps on Linux:
1. `brew tap homebrew/cask-fonts`
2. `brew install font-inconsolata` or `brew install font-hack-nerd-font`

With the outputs:
```sh
Warning: No available formula with the name "font-inconsolata". Did you mean fonts-encodings?
==> Searching for similarly named formulae...
==> Formulae
fonts-encodings
```
or
```sh
Warning: No available formula with the name "font-hack-nerd-font".
==> Searching for similarly named formulae...
Error: No formulae found for font-hack-nerd-font.
Error: Process completed with exit code 1.
```

You can repro this issue on https://github.com/Goooler/FiraCode/pull/1.

### Command that failed

`brew install font-inconsolata` or `brew install font-hack-nerd-font`

### Output of command with `--verbose --debug`

```shell
==> Tapping homebrew/cask-fonts
Cloning into '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts'...
Tapped 2007 casks (2,042 files, 16.2MB).
Warning: No available formula with the name "font-inconsolata". Did you mean fonts-encodings?
==> Searching for similarly named formulae...
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Linuxbrew/3.6.20\ \(Linux\;\ x86_64\ Ubuntu\ 22.04.1\ LTS\)\ curl/7.81.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/code\?q=user\%3AHomebrew\+path\%3AFormula\+path\%3ACasks\+path\%3A.\+filename\%3Afont-inconsolata\+extension\%3Arb\&per_page=100 --header Accept:\ application/vnd.github\+json --write-out '
'\%\{http_code\} --header X-GitHub-Api-Version:2022-11-28 --dump-header /tmp/github_api_headers20230126-3669-i6qknh
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/fonts-encodings.rb
==> Formulae
fonts-encodings

To install fonts-encodings, run:
  brew install fonts-encodings
Warning: No available formula with the name "font-hack-nerd-font".
==> Searching for similarly named formulae...
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Linuxbrew/3.6.20\ \(Linux\;\ x86_64\ Ubuntu\ 22.04.1\ LTS\)\ curl/7.81.0 --header Accept-Language:\ en --retry 3 --location https://api.github.com/search/code\?q=user\%3AHomebrew\+path\%3AFormula\+path\%3ACasks\+path\%3A.\+filename\%3Afont-hack-nerd-font\+extension\%3Arb\&per_page=100 --header Accept:\ application/vnd.github\+json --write-out '
'\%\{http_code\} --header X-GitHub-Api-Version:2022-11-28 --dump-header /tmp/github_api_headers20230126-3920-6iux0i
Error: No formulae found for font-hack-nerd-font.
Error: Kernel.exit
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:165:in `exit'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/utils.rb:165:in `odie'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:332:in `rescue in install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/cmd/install.rb:146:in `install'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/brew.rb:98:in `<main>'
Error: Process completed with exit code 1.
```

### Output of `brew doctor --verbose`

https://github.com/Goooler/FiraCode/actions/runs/4016275684/jobs/6899083883

```shell
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/node/cppgc/common.h
  /usr/local/include/node/js_native_api.h
  /usr/local/include/node/js_native_api_types.h
  /usr/local/include/node/libplatform/libplatform-export.h
  /usr/local/include/node/libplatform/libplatform.h
  /usr/local/include/node/libplatform/v8-tracing.h
  /usr/local/include/node/node.h
  /usr/local/include/node/node_api.h
  /usr/local/include/node/node_api_types.h
  /usr/local/include/node/node_buffer.h
  /usr/local/include/node/node_object_wrap.h
  /usr/local/include/node/node_version.h
  /usr/local/include/node/openssl/aes.h
  /usr/local/include/node/openssl/archs/BSD-x86/asm/crypto/buildinf.h
  
  ...
```

### Output of `brew tap`

```shell
homebrew/cask-fonts
homebrew/core
```

**Comment by p-linnane** [comment]
This repository is for `cask` files, which only work on macOS. Please take a look at https://github.com/Homebrew/homebrew-linux-fonts.

**Comment by Goooler** [comment]
Thanks

**Comment by aphive** [comment]
Having same issues, this worked not more than 2 months ago on my Pop! OS laptop. now I can't install.

Thanks for the pointer to the linux-fonts.
