### ISSUE TITLE
`font-im-fell-types` doesn't install, source is offline

### ISSUE THREAD

**Issue by janurskremer** [Homebrew/homebrew-cask-fonts#9219]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match / SHA256 mismatch](https://docs.brew.sh/Common-Issues#cask---checksum-does-not-match) error (do not open an issue before trying to open a PR to fix first).

### Description of issue

I tried to install `font-im-fell-types` but it doesn't work. I checked the [source url](https://iginomarini.com/fell) and it seems to be offline. 

The new homepage seems to be [ikern.space](ikern.space) but the author links to Google Fonts.

Maybe we could replace the source with the different Google Font sources as in other `font-im-fell-...` casks.

### Command that failed

brew install font-im-fell-types

### Output of command with `--verbose --debug`

```shell
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading font-im-fell-types
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::NullLoader): loading font-im-fell-types
/usr/local/Homebrew/Library/Homebrew/brew.rb (Cask::CaskLoader::FromNameLoader): loading font-im-fell-types
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.16-75-g2fe08b1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.7.4\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://iginomarini.com/fell/wp-content/uploads/IMFellTypesClass.zip
==> Downloading https://iginomarini.com/fell/wp-content/uploads/IMFellTypesClass.zip
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.16-75-g2fe08b1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.7.4\)\ curl/8.4.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head https://iginomarini.com/fell/wp-content/uploads/IMFellTypesClass.zip
/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.2.16-75-g2fe08b1\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 12.7.4\)\ curl/8.4.0 --header Accept-Language:\ en --fail --retry 3 --remote-time --output /Users/jan/Library/Caches/Homebrew/downloads/7f9ead44776ba75265ac4832275ccbc8d954c1d722addea4af27340cff82f442--IMFellTypesClass.zip.incomplete --location https://iginomarini.com/fell/wp-content/uploads/IMFellTypesClass.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to iginomarini.com port 443 after 75004 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to iginomarini.com port 443 after 75003 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to iginomarini.com port 443 after 75003 ms: Couldn't connect to server
Warning: Problem : timeout. Will retry in 4 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to iginomarini.com port 443 after 75003 ms: Couldn't connect to server
Error: Download failed on Cask 'font-im-fell-types' with message: Download failed: https://iginomarini.com/fell/wp-content/uploads/IMFellTypesClass.zip
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:447:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:444:in `fetch'
/usr/local/Homebrew/Library/Homebrew/downloadable.rb:87:in `fetch'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:167:in `bind_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:55:in `fetch'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:186:in `download'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:71:in `fetch'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:247:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:236:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:236:in `run'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `bind_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/call_validation.rb:270:in `validate_call'
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/ruby/3.1.0/gems/sorbet-runtime-0.5.11327/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
/usr/local/Homebrew/Library/Homebrew/brew.rb:89:in `<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

### Output of `brew doctor` and `brew config`

```shell
Your system is ready to brew.

HOMEBREW_VERSION: 4.2.16-75-g2fe08b1
ORIGIN: https://github.com/Homebrew/brew
HEAD: 2fe08b139ebb467f2e78ab354cd2e7fd4f9fddae
Last commit: 61 minutes ago
Core tap HEAD: b751553af0cde88560b214e0db1233d0a9dca8d7
Core tap last commit: 3 hours ago
Core tap JSON: 04 Apr 08:54 UTC
Core cask tap JSON: 04 Apr 08:54 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: nvim
HOMEBREW_MAKE_JOBS: 4
HOMEBREW_SORBET_RUNTIME: set
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 14.0.0 build 1400
Git: 2.37.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 12.7.4-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

### Output of `brew tap`

```shell
homebrew/autoupdate
homebrew/bundle
homebrew/cask-fonts
homebrew/core
homebrew/services
```

**Comment by bevanjkay** [comment]
The fonts retrieved from `google-fonts` are managed by a script, and all available fonts are already included in the repo.
If the font here is not available anymore then the cask should be disabled.
